// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {Vector3} from '../Vector3';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class AgentSetAppearancePacket implements Packet
{
    name = 'AgentSetAppearance';
    flags = MessageFlags.Zerocoded | MessageFlags.FrequencyLow;
    id = 4294901844;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
        SerialNum: number;
        Size: Vector3;
    };
    WearableData: {
        CacheID: UUID;
        TextureIndex: number;
    }[];
    ObjectData: {
        TextureEntry: string;
    };
    VisualParam: {
        ParamValue: number;
    }[];

    getSize(): number
    {
        return ((17) * this.WearableData.length) + (this.ObjectData['TextureEntry'].length + 2) + ((1) * this.VisualParam.length) + 50;
    }

}
