// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class AgentThrottlePacket implements Packet
{
    name = 'AgentThrottle';
    flags = MessageFlags.Zerocoded | MessageFlags.FrequencyLow;
    id = 4294901841;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
        CircuitCode: number;
    };
    Throttle: {
        GenCounter: number;
        Throttles: string;
    };

    getSize(): number
    {
        return (this.Throttle['Throttles'].length + 1) + 40;
    }

}
