// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {Vector3} from '../Vector3';
import {Quaternion} from '../Quaternion';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class AgentUpdatePacket implements Packet
{
    name = 'AgentUpdate';
    flags = MessageFlags.Zerocoded | MessageFlags.FrequencyHigh;
    id = 4;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
        BodyRotation: Quaternion;
        HeadRotation: Quaternion;
        State: number;
        CameraCenter: Vector3;
        CameraAtAxis: Vector3;
        CameraLeftAxis: Vector3;
        CameraUpAxis: Vector3;
        Far: number;
        ControlFlags: number;
        Flags: number;
    };

    getSize(): number
    {
        return 114;
    }

}
