// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class AgentPausePacket implements Packet
{
    name = 'AgentPause';
    flags = MessageFlags.FrequencyLow;
    id = 4294901838;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
        SerialNum: number;
    };

    getSize(): number
    {
        return 36;
    }

}
