// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class AtomicPassObjectPacket implements Packet
{
    name = 'AtomicPassObject';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyHigh;
    id = 28;

    TaskData: {
        TaskID: UUID;
        AttachmentNeedsSave: boolean;
    };

    getSize(): number
    {
        return 17;
    }

}
