// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class AvatarPickerRequestBackendPacket implements Packet
{
    name = 'AvatarPickerRequestBackend';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = 4294901787;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
        QueryID: UUID;
        GodLevel: number;
    };
    Data: {
        Name: string;
    };

    getSize(): number
    {
        return (this.Data['Name'].length + 1) + 49;
    }

}
