// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class ChangeInventoryItemFlagsPacket implements Packet
{
    name = 'ChangeInventoryItemFlags';
    flags = MessageFlags.FrequencyLow;
    id = 4294902031;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    InventoryData: {
        ItemID: UUID;
        Flags: number;
    }[];

    getSize(): number
    {
        return ((20) * this.InventoryData.length) + 33;
    }

}
