// This file has been automatically generated by writePacketClasses.js

import Long = require('long');
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class CheckParcelAuctionsPacket implements Packet
{
    name = 'CheckParcelAuctions';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = 4294901993;

    RegionData: {
        RegionHandle: Long;
    }[];

    getSize(): number
    {
        return ((8) * this.RegionData.length) + 1;
    }

}
