// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class ClassifiedDeletePacket implements Packet
{
    name = 'ClassifiedDelete';
    flags = MessageFlags.FrequencyLow;
    id = 4294901806;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    Data: {
        ClassifiedID: UUID;
    };

    getSize(): number
    {
        return 48;
    }

}
