// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {Vector3} from '../Vector3';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class ClassifiedInfoReplyPacket implements Packet
{
    name = 'ClassifiedInfoReply';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = 4294901804;

    AgentData: {
        AgentID: UUID;
    };
    Data: {
        ClassifiedID: UUID;
        CreatorID: UUID;
        CreationDate: number;
        ExpirationDate: number;
        Category: number;
        Name: string;
        Desc: string;
        ParcelID: UUID;
        ParentEstate: number;
        SnapshotID: UUID;
        SimName: string;
        PosGlobal: Vector3;
        ParcelName: string;
        ClassifiedFlags: number;
        PriceForListing: number;
    };

    getSize(): number
    {
        return (this.Data['Name'].length + 1 + this.Data['Desc'].length + 2 + this.Data['SimName'].length + 1 + this.Data['ParcelName'].length + 1) + 125;
    }

}
