// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class ClearFollowCamPropertiesPacket implements Packet
{
    name = 'ClearFollowCamProperties';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = 4294901920;

    ObjectData: {
        ObjectID: UUID;
    };

    getSize(): number
    {
        return 16;
    }

}
