// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class ConfirmAuctionStartPacket implements Packet
{
    name = 'ConfirmAuctionStart';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = 4294901990;

    AuctionData: {
        ParcelID: UUID;
        AuctionID: number;
    };

    getSize(): number
    {
        return 20;
    }

     writeToBuffer(buf: Buffer, pos: number): number
     {
         const startPos = pos;
         this.AuctionData['ParcelID'].writeToBuffer(buf, pos);
         pos += 16;
         buf.writeUInt32LE(this.AuctionData['AuctionID'], pos);
         pos += 4;
         return pos - startPos;
     }

     readFromBuffer(buf: Buffer, pos: number): number
     {
         const startPos = pos;
         const newObjAuctionData: {
             ParcelID: UUID,
             AuctionID: number
         } = {
             ParcelID: UUID.zero(),
             AuctionID: 0
         };
         newObjAuctionData['ParcelID'] = new UUID(buf, pos);
         pos += 16;
         newObjAuctionData['AuctionID'] = buf.readUInt32LE(pos);
         pos += 4;
         this.AuctionData = newObjAuctionData;
         return pos - startPos;
     }
}

