// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class CreateNewOutfitAttachmentsPacket implements Packet
{
    name = 'CreateNewOutfitAttachments';
    flags = MessageFlags.FrequencyLow;
    id = 4294902158;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    HeaderData: {
        NewFolderID: UUID;
    };
    ObjectData: {
        OldItemID: UUID;
        OldFolderID: UUID;
    }[];

    getSize(): number
    {
        return ((32) * this.ObjectData.length) + 49;
    }

}
