// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class CreateLandmarkForEventPacket implements Packet
{
    name = 'CreateLandmarkForEvent';
    flags = MessageFlags.Zerocoded | MessageFlags.FrequencyLow;
    id = 4294902066;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    EventData: {
        EventID: number;
    };
    InventoryBlock: {
        FolderID: UUID;
        Name: string;
    };

    getSize(): number
    {
        return (this.InventoryBlock['Name'].length + 1) + 52;
    }

     writeToBuffer(buf: Buffer, pos: number): number
     {
         const startPos = pos;
         this.AgentData['AgentID'].writeToBuffer(buf, pos);
         pos += 16;
         this.AgentData['SessionID'].writeToBuffer(buf, pos);
         pos += 16;
         buf.writeUInt32LE(this.EventData['EventID'], pos);
         pos += 4;
         this.InventoryBlock['FolderID'].writeToBuffer(buf, pos);
         pos += 16;
         buf.write(this.InventoryBlock['Name'], pos);
         pos += this.InventoryBlock['Name'].length;
         return pos - startPos;
     }

     readFromBuffer(buf: Buffer, pos: number): number
     {
         const startPos = pos;
         const newObjAgentData: {
             AgentID: UUID,
             SessionID: UUID
         } = {
             AgentID: UUID.zero(),
             SessionID: UUID.zero()
         };
         newObjAgentData['AgentID'] = new UUID(buf, pos);
         pos += 16;
         newObjAgentData['SessionID'] = new UUID(buf, pos);
         pos += 16;
         this.AgentData = newObjAgentData;
         const newObjEventData: {
             EventID: number
         } = {
             EventID: 0
         };
         newObjEventData['EventID'] = buf.readUInt32LE(pos);
         pos += 4;
         this.EventData = newObjEventData;
         const newObjInventoryBlock: {
             FolderID: UUID,
             Name: string
         } = {
             FolderID: UUID.zero(),
             Name: ''
         };
         newObjInventoryBlock['FolderID'] = new UUID(buf, pos);
         pos += 16;
         newObjInventoryBlock['Name'] = buf.toString('utf8', pos, length);
         pos += length;
         this.InventoryBlock = newObjInventoryBlock;
         return pos - startPos;
     }
}

