// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class CreateInventoryItemPacket implements Packet
{
    name = 'CreateInventoryItem';
    flags = MessageFlags.Zerocoded | MessageFlags.FrequencyLow;
    id = 4294902065;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    InventoryBlock: {
        CallbackID: number;
        FolderID: UUID;
        TransactionID: UUID;
        NextOwnerMask: number;
        Type: number;
        InvType: number;
        WearableType: number;
        Name: string;
        Description: string;
    };

    getSize(): number
    {
        return (this.InventoryBlock['Name'].length + 1 + this.InventoryBlock['Description'].length + 1) + 75;
    }

}
