// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class CreateInventoryFolderPacket implements Packet
{
    name = 'CreateInventoryFolder';
    flags = MessageFlags.FrequencyLow;
    id = 4294902033;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    FolderData: {
        FolderID: UUID;
        ParentID: UUID;
        Type: number;
        Name: string;
    };

    getSize(): number
    {
        return (this.FolderData['Name'].length + 1) + 65;
    }

}
