// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class DeclineFriendshipPacket implements Packet
{
    name = 'DeclineFriendship';
    flags = MessageFlags.FrequencyLow;
    id = 4294902058;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    TransactionBlock: {
        TransactionID: UUID;
    };

    getSize(): number
    {
        return 48;
    }

}
