// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class DirPlacesQueryPacket implements Packet
{
    name = 'DirPlacesQuery';
    flags = MessageFlags.Zerocoded | MessageFlags.FrequencyLow;
    id = 4294901793;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    QueryData: {
        QueryID: UUID;
        QueryText: string;
        QueryFlags: number;
        Category: number;
        SimName: string;
        QueryStart: number;
    };

    getSize(): number
    {
        return (this.QueryData['QueryText'].length + 1 + this.QueryData['SimName'].length + 1) + 57;
    }

}
