// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class EmailMessageReplyPacket implements Packet
{
    name = 'EmailMessageReply';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = 4294902096;

    DataBlock: {
        ObjectID: UUID;
        More: number;
        Time: number;
        FromAddress: string;
        Subject: string;
        Data: string;
        MailFilter: string;
    };

    getSize(): number
    {
        return (this.DataBlock['FromAddress'].length + 1 + this.DataBlock['Subject'].length + 1 + this.DataBlock['Data'].length + 2 + this.DataBlock['MailFilter'].length + 1) + 24;
    }

}
