// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class EventGodDeletePacket implements Packet
{
    name = 'EventGodDelete';
    flags = MessageFlags.FrequencyLow;
    id = 4294901943;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    EventData: {
        EventID: number;
    };
    QueryData: {
        QueryID: UUID;
        QueryText: string;
        QueryFlags: number;
        QueryStart: number;
    };

    getSize(): number
    {
        return (this.QueryData['QueryText'].length + 1) + 60;
    }

     writeToBuffer(buf: Buffer, pos: number): number
     {
         const startPos = pos;
         this.AgentData['AgentID'].writeToBuffer(buf, pos);
         pos += 16;
         this.AgentData['SessionID'].writeToBuffer(buf, pos);
         pos += 16;
         buf.writeUInt32LE(this.EventData['EventID'], pos);
         pos += 4;
         this.QueryData['QueryID'].writeToBuffer(buf, pos);
         pos += 16;
         buf.write(this.QueryData['QueryText'], pos);
         pos += this.QueryData['QueryText'].length;
         buf.writeUInt32LE(this.QueryData['QueryFlags'], pos);
         pos += 4;
         buf.writeInt32LE(this.QueryData['QueryStart'], pos);
         pos += 4;
         return pos - startPos;
     }

     readFromBuffer(buf: Buffer, pos: number): number
     {
         const startPos = pos;
         const newObjAgentData: {
             AgentID: UUID,
             SessionID: UUID
         } = {
             AgentID: UUID.zero(),
             SessionID: UUID.zero()
         };
         newObjAgentData['AgentID'] = new UUID(buf, pos);
         pos += 16;
         newObjAgentData['SessionID'] = new UUID(buf, pos);
         pos += 16;
         this.AgentData = newObjAgentData;
         const newObjEventData: {
             EventID: number
         } = {
             EventID: 0
         };
         newObjEventData['EventID'] = buf.readUInt32LE(pos);
         pos += 4;
         this.EventData = newObjEventData;
         const newObjQueryData: {
             QueryID: UUID,
             QueryText: string,
             QueryFlags: number,
             QueryStart: number
         } = {
             QueryID: UUID.zero(),
             QueryText: '',
             QueryFlags: 0,
             QueryStart: 0
         };
         newObjQueryData['QueryID'] = new UUID(buf, pos);
         pos += 16;
         newObjQueryData['QueryText'] = buf.toString('utf8', pos, length);
         pos += length;
         newObjQueryData['QueryFlags'] = buf.readUInt32LE(pos);
         pos += 4;
         newObjQueryData['QueryStart'] = buf.readInt32LE(pos);
         pos += 4;
         this.QueryData = newObjQueryData;
         return pos - startPos;
     }
}

