// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class FreezeUserPacket implements Packet
{
    name = 'FreezeUser';
    flags = MessageFlags.FrequencyLow;
    id = 4294901928;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    Data: {
        TargetID: UUID;
        Flags: number;
    };

    getSize(): number
    {
        return 52;
    }

}
