// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class GetScriptRunningPacket implements Packet
{
    name = 'GetScriptRunning';
    flags = MessageFlags.FrequencyLow;
    id = 4294902003;

    Script: {
        ObjectID: UUID;
        ItemID: UUID;
    };

    getSize(): number
    {
        return 32;
    }

}
