// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class GroupRoleDataRequestPacket implements Packet
{
    name = 'GroupRoleDataRequest';
    flags = MessageFlags.FrequencyLow;
    id = 4294902131;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    GroupData: {
        GroupID: UUID;
        RequestID: UUID;
    };

    getSize(): number
    {
        return 64;
    }

}
