// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class GroupNoticeAddPacket implements Packet
{
    name = 'GroupNoticeAdd';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = 4294901821;

    AgentData: {
        AgentID: UUID;
    };
    MessageBlock: {
        ToGroupID: UUID;
        ID: UUID;
        Dialog: number;
        FromAgentName: string;
        Message: string;
        BinaryBucket: string;
    };

    getSize(): number
    {
        return (this.MessageBlock['FromAgentName'].length + 1 + this.MessageBlock['Message'].length + 2 + this.MessageBlock['BinaryBucket'].length + 2) + 49;
    }

}
