// This file has been automatically generated by writePacketClasses.js

import Long = require('long');
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class ImprovedTerseObjectUpdatePacket implements Packet
{
    name = 'ImprovedTerseObjectUpdate';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyHigh;
    id = 15;

    RegionData: {
        RegionHandle: Long;
        TimeDilation: number;
    };
    ObjectData: {
        Data: string;
        TextureEntry: string;
    }[];

    getSize(): number
    {
        return ((this.calculateVarVarSize(this.ObjectData, 'Data', 1) + this.calculateVarVarSize(this.ObjectData, 'TextureEntry', 2)) * this.ObjectData.length) + 11;
    }

    calculateVarVarSize(block: object[], paramName: string, extraPerVar: number): number
    {
        let size = 0;
        block.forEach((bl: any) =>
        {
            size += bl[paramName].length + extraPerVar;
        });
        return size;
    }

     writeToBuffer(buf: Buffer, pos: number): number
     {
         const startPos = pos;
         buf.writeInt32LE(this.RegionData['RegionHandle'].low, pos);
         pos += 4;
         buf.writeInt32LE(this.RegionData['RegionHandle'].high, pos);
         pos += 4;
         buf.writeUInt16LE(this.RegionData['TimeDilation'], pos);
         pos += 2;
         const count = this.ObjectData.length;
         buf.writeUInt8(this.ObjectData.length, pos++);
         for (let i = 0; i < count; i++)
         {
             buf.write(this.ObjectData[i]['Data'], pos);
             pos += this.ObjectData[i]['Data'].length;
             buf.write(this.ObjectData[i]['TextureEntry'], pos);
             pos += this.ObjectData[i]['TextureEntry'].length;
         }
         return pos - startPos;
     }

     readFromBuffer(buf: Buffer, pos: number): number
     {
         const startPos = pos;
         const newObjRegionData: {
             RegionHandle: Long,
             TimeDilation: number
         } = {
             RegionHandle: Long.ZERO,
             TimeDilation: 0
         };
         newObjRegionData['RegionHandle'] = new Long(buf.readInt32LE(pos), buf.readInt32LE(pos+4));
         pos += 8;
         newObjRegionData['TimeDilation'] = buf.readUInt16LE(pos);
         pos += 2;
         this.RegionData = newObjRegionData;
         const count = buf.readUInt8(pos++);
         this.ObjectData = [];
         for (let i = 0; i < count; i++)
         {
             const newObjObjectData: {
                 Data: string,
                 TextureEntry: string
             } = {
                 Data: '',
                 TextureEntry: ''
             };
             newObjObjectData['Data'] = buf.toString('utf8', pos, length);
             pos += length;
             newObjObjectData['TextureEntry'] = buf.toString('utf8', pos, length);
             pos += length;
             this.ObjectData.push(newObjObjectData);
         }
         return pos - startPos;
     }
}

