// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class KillChildAgentsPacket implements Packet
{
    name = 'KillChildAgents';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = 4294902002;

    IDBlock: {
        AgentID: UUID;
    };

    getSize(): number
    {
        return 16;
    }

}
