// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class LeaveGroupReplyPacket implements Packet
{
    name = 'LeaveGroupReply';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = 4294902108;

    AgentData: {
        AgentID: UUID;
    };
    GroupData: {
        GroupID: UUID;
        Success: boolean;
    };

    getSize(): number
    {
        return 33;
    }

}
