// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class LinkInventoryItemPacket implements Packet
{
    name = 'LinkInventoryItem';
    flags = MessageFlags.Zerocoded | MessageFlags.FrequencyLow;
    id = 4294902186;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    InventoryBlock: {
        CallbackID: number;
        FolderID: UUID;
        TransactionID: UUID;
        OldItemID: UUID;
        Type: number;
        InvType: number;
        Name: string;
        Description: string;
    };

    getSize(): number
    {
        return (this.InventoryBlock['Name'].length + 1 + this.InventoryBlock['Description'].length + 1) + 86;
    }

}
