// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class LiveHelpGroupReplyPacket implements Packet
{
    name = 'LiveHelpGroupReply';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = 4294902140;

    ReplyData: {
        RequestID: UUID;
        GroupID: UUID;
        Selection: string;
    };

    getSize(): number
    {
        return (this.ReplyData['Selection'].length + 1) + 32;
    }

}
