// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class MapLayerRequestPacket implements Packet
{
    name = 'MapLayerRequest';
    flags = MessageFlags.FrequencyLow;
    id = 4294902165;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
        Flags: number;
        EstateID: number;
        Godlike: boolean;
    };

    getSize(): number
    {
        return 41;
    }

}
