// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class MapNameRequestPacket implements Packet
{
    name = 'MapNameRequest';
    flags = MessageFlags.FrequencyLow;
    id = 4294902168;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
        Flags: number;
        EstateID: number;
        Godlike: boolean;
    };
    NameData: {
        Name: string;
    };

    getSize(): number
    {
        return (this.NameData['Name'].length + 1) + 41;
    }

}
