// This file has been automatically generated by writePacketClasses.js

import Long = require('long');
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class NearestLandingRegionReplyPacket implements Packet
{
    name = 'NearestLandingRegionReply';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = 4294901905;

    LandingRegionData: {
        RegionHandle: Long;
    };

    getSize(): number
    {
        return 8;
    }

}
