// This file has been automatically generated by writePacketClasses.js

import Long = require('long');
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class NearestLandingRegionRequestPacket implements Packet
{
    name = 'NearestLandingRegionRequest';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = 4294901904;

    RequestingRegionData: {
        RegionHandle: Long;
    };

    getSize(): number
    {
        return 8;
    }

}
