// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {Vector3} from '../Vector3';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class ObjectGrabPacket implements Packet
{
    name = 'ObjectGrab';
    flags = MessageFlags.Zerocoded | MessageFlags.FrequencyLow;
    id = 4294901877;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    ObjectData: {
        LocalID: number;
        GrabOffset: Vector3;
    };
    SurfaceInfo: {
        UVCoord: Vector3;
        STCoord: Vector3;
        FaceIndex: number;
        Position: Vector3;
        Normal: Vector3;
        Binormal: Vector3;
    }[];

    getSize(): number
    {
        return ((64) * this.SurfaceInfo.length) + 49;
    }

}
