// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class ObjectDeletePacket implements Packet
{
    name = 'ObjectDelete';
    flags = MessageFlags.Zerocoded | MessageFlags.FrequencyLow;
    id = 4294901849;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
        Force: boolean;
    };
    ObjectData: {
        ObjectLocalID: number;
    }[];

    getSize(): number
    {
        return ((4) * this.ObjectData.length) + 34;
    }

}
