// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {Quaternion} from '../Quaternion';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class ObjectSpinUpdatePacket implements Packet
{
    name = 'ObjectSpinUpdate';
    flags = MessageFlags.Zerocoded | MessageFlags.FrequencyLow;
    id = 4294901881;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    ObjectData: {
        ObjectID: UUID;
        Rotation: Quaternion;
    };

    getSize(): number
    {
        return 60;
    }

}
