// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class ObjectSpinStartPacket implements Packet
{
    name = 'ObjectSpinStart';
    flags = MessageFlags.Zerocoded | MessageFlags.FrequencyLow;
    id = 4294901880;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    ObjectData: {
        ObjectID: UUID;
    };

    getSize(): number
    {
        return 48;
    }

}
