// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class ObjectSaleInfoPacket implements Packet
{
    name = 'ObjectSaleInfo';
    flags = MessageFlags.Zerocoded | MessageFlags.FrequencyLow;
    id = 4294901866;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    ObjectData: {
        LocalID: number;
        SaleType: number;
        SalePrice: number;
    }[];

    getSize(): number
    {
        return ((9) * this.ObjectData.length) + 33;
    }

}
