// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class ParcelDwellReplyPacket implements Packet
{
    name = 'ParcelDwellReply';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = 4294901979;

    AgentData: {
        AgentID: UUID;
    };
    Data: {
        LocalID: number;
        ParcelID: UUID;
        Dwell: number;
    };

    getSize(): number
    {
        return 40;
    }

}
