// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class ParcelDividePacket implements Packet
{
    name = 'ParcelDivide';
    flags = MessageFlags.FrequencyLow;
    id = 4294901971;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    ParcelData: {
        West: number;
        South: number;
        East: number;
        North: number;
    };

    getSize(): number
    {
        return 48;
    }

}
