// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class ParcelGodForceOwnerPacket implements Packet
{
    name = 'ParcelGodForceOwner';
    flags = MessageFlags.Zerocoded | MessageFlags.FrequencyLow;
    id = 4294901974;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    Data: {
        OwnerID: UUID;
        LocalID: number;
    };

    getSize(): number
    {
        return 52;
    }

}
