// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class ParcelBuyPacket implements Packet
{
    name = 'ParcelBuy';
    flags = MessageFlags.Zerocoded | MessageFlags.FrequencyLow;
    id = 4294901973;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    Data: {
        GroupID: UUID;
        IsGroupOwned: boolean;
        RemoveContribution: boolean;
        LocalID: number;
        Final: boolean;
    };
    ParcelData: {
        Price: number;
        Area: number;
    };

    getSize(): number
    {
        return 63;
    }

}
