// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class ParcelAccessListRequestPacket implements Packet
{
    name = 'ParcelAccessListRequest';
    flags = MessageFlags.Zerocoded | MessageFlags.FrequencyLow;
    id = 4294901975;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    Data: {
        SequenceID: number;
        Flags: number;
        LocalID: number;
    };

    getSize(): number
    {
        return 44;
    }

}
