// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class PayPriceReplyPacket implements Packet
{
    name = 'PayPriceReply';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = 4294901922;

    ObjectData: {
        ObjectID: UUID;
        DefaultPayPrice: number;
    };
    ButtonData: {
        PayButton: number;
    }[];

    getSize(): number
    {
        return ((4) * this.ButtonData.length) + 21;
    }

}
