// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class PickDeletePacket implements Packet
{
    name = 'PickDelete';
    flags = MessageFlags.FrequencyLow;
    id = 4294901946;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    Data: {
        PickID: UUID;
    };

    getSize(): number
    {
        return 48;
    }

}
