// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class RemoveInventoryFolderPacket implements Packet
{
    name = 'RemoveInventoryFolder';
    flags = MessageFlags.FrequencyLow;
    id = 4294902036;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    FolderData: {
        FolderID: UUID;
    }[];

    getSize(): number
    {
        return ((16) * this.FolderData.length) + 33;
    }

     writeToBuffer(buf: Buffer, pos: number): number
     {
         const startPos = pos;
         this.AgentData['AgentID'].writeToBuffer(buf, pos);
         pos += 16;
         this.AgentData['SessionID'].writeToBuffer(buf, pos);
         pos += 16;
         const count = this.FolderData.length;
         buf.writeUInt8(this.FolderData.length, pos++);
         for (let i = 0; i < count; i++)
         {
             this.FolderData[i]['FolderID'].writeToBuffer(buf, pos);
             pos += 16;
         }
         return pos - startPos;
     }

     readFromBuffer(buf: Buffer, pos: number): number
     {
         const startPos = pos;
         const newObjAgentData: {
             AgentID: UUID,
             SessionID: UUID
         } = {
             AgentID: UUID.zero(),
             SessionID: UUID.zero()
         };
         newObjAgentData['AgentID'] = new UUID(buf, pos);
         pos += 16;
         newObjAgentData['SessionID'] = new UUID(buf, pos);
         pos += 16;
         this.AgentData = newObjAgentData;
         const count = buf.readUInt8(pos++);
         this.FolderData = [];
         for (let i = 0; i < count; i++)
         {
             const newObjFolderData: {
                 FolderID: UUID
             } = {
                 FolderID: UUID.zero()
             };
             newObjFolderData['FolderID'] = new UUID(buf, pos);
             pos += 16;
             this.FolderData.push(newObjFolderData);
         }
         return pos - startPos;
     }
}

