// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class ReplyTaskInventoryPacket implements Packet
{
    name = 'ReplyTaskInventory';
    flags = MessageFlags.Trusted | MessageFlags.Zerocoded | MessageFlags.FrequencyLow;
    id = 4294902050;

    InventoryData: {
        TaskID: UUID;
        Serial: number;
        Filename: string;
    };

    getSize(): number
    {
        return (this.InventoryData['Filename'].length + 1) + 18;
    }

}
