// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class RequestGodlikePowersPacket implements Packet
{
    name = 'RequestGodlikePowers';
    flags = MessageFlags.FrequencyLow;
    id = 4294902017;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    RequestBlock: {
        Godlike: boolean;
        Token: UUID;
    };

    getSize(): number
    {
        return 49;
    }

}
