// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class ScriptAnswerYesPacket implements Packet
{
    name = 'ScriptAnswerYes';
    flags = MessageFlags.FrequencyLow;
    id = 4294901892;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    Data: {
        TaskID: UUID;
        ItemID: UUID;
        Questions: number;
    };

    getSize(): number
    {
        return 68;
    }

}
