// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class ScriptMailRegistrationPacket implements Packet
{
    name = 'ScriptMailRegistration';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = 4294902178;

    DataBlock: {
        TargetIP: string;
        TargetPort: number;
        TaskID: UUID;
        Flags: number;
    };

    getSize(): number
    {
        return (this.DataBlock['TargetIP'].length + 1) + 22;
    }

}
