// This file has been automatically generated by writePacketClasses.js

import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class SetCPURatioPacket implements Packet
{
    name = 'SetCPURatio';
    flags = MessageFlags.FrequencyLow;
    id = 4294902087;

    Data: {
        Ratio: number;
    };

    getSize(): number
    {
        return 1;
    }

     writeToBuffer(buf: Buffer, pos: number): number
     {
         const startPos = pos;
         buf.writeUInt8(this.Data['Ratio'], pos++);
         return pos - startPos;
     }

     readFromBuffer(buf: Buffer, pos: number): number
     {
         const startPos = pos;
         const newObjData: {
             Ratio: number
         } = {
             Ratio: 0
         };
         newObjData['Ratio'] = buf.readUInt8(pos++);
         this.Data = newObjData;
         return pos - startPos;
     }
}

