// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class SetGroupContributionPacket implements Packet
{
    name = 'SetGroupContribution';
    flags = MessageFlags.FrequencyLow;
    id = 4294902129;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    Data: {
        GroupID: UUID;
        Contribution: number;
    };

    getSize(): number
    {
        return 52;
    }

}
