// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class SetSimStatusInDatabasePacket implements Packet
{
    name = 'SetSimStatusInDatabase';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = 4294901782;

    Data: {
        RegionID: UUID;
        HostName: string;
        X: number;
        Y: number;
        PID: number;
        AgentCount: number;
        TimeToLive: number;
        Status: string;
    };

    getSize(): number
    {
        return (this.Data['HostName'].length + 1 + this.Data['Status'].length + 1) + 36;
    }

}
