// This file has been automatically generated by writePacketClasses.js

import Long = require('long');
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class SimStatsPacket implements Packet
{
    name = 'SimStats';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = 4294901900;

    Region: {
        RegionX: number;
        RegionY: number;
        RegionFlags: number;
        ObjectCapacity: number;
    };
    Stat: {
        StatID: number;
        StatValue: number;
    }[];
    PidStat: {
        PID: number;
    };
    RegionInfo: {
        RegionFlagsExtended: Long;
    }[];

    getSize(): number
    {
        return ((8) * this.Stat.length) + ((8) * this.RegionInfo.length) + 22;
    }

}
