// This file has been automatically generated by writePacketClasses.js

import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class SimulatorMapUpdatePacket implements Packet
{
    name = 'SimulatorMapUpdate';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = 4294901765;

    MapData: {
        Flags: number;
    };

    getSize(): number
    {
        return 4;
    }

}
