// This file has been automatically generated by writePacketClasses.js

import {Vector3} from '../Vector3';
import Long = require('long');
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class SimulatorViewerTimeMessagePacket implements Packet
{
    name = 'SimulatorViewerTimeMessage';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = 4294901910;

    TimeInfo: {
        UsecSinceStart: Long;
        SecPerDay: number;
        SecPerYear: number;
        SunDirection: Vector3;
        SunPhase: number;
        SunAngVelocity: Vector3;
    };

    getSize(): number
    {
        return 44;
    }

}
