// This file has been automatically generated by writePacketClasses.js

import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class SimulatorMapUpdatePacket implements Packet
{
    name = 'SimulatorMapUpdate';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = 4294901765;

    MapData: {
        Flags: number;
    };

    getSize(): number
    {
        return 4;
    }

     writeToBuffer(buf: Buffer, pos: number): number
     {
         const startPos = pos;
         buf.writeUInt32LE(this.MapData['Flags'], pos);
         pos += 4;
         return pos - startPos;
     }

     readFromBuffer(buf: Buffer, pos: number): number
     {
         const startPos = pos;
         const newObjMapData: {
             Flags: number
         } = {
             Flags: 0
         };
         newObjMapData['Flags'] = buf.readUInt32LE(pos);
         pos += 4;
         this.MapData = newObjMapData;
         return pos - startPos;
     }
}

