// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class StartAuctionPacket implements Packet
{
    name = 'StartAuction';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = 4294901989;

    AgentData: {
        AgentID: UUID;
    };
    ParcelData: {
        ParcelID: UUID;
        SnapshotID: UUID;
        Name: string;
    };

    getSize(): number
    {
        return (this.ParcelData['Name'].length + 1) + 48;
    }

}
