// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class StartLurePacket implements Packet
{
    name = 'StartLure';
    flags = MessageFlags.FrequencyLow;
    id = 4294901830;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    Info: {
        LureType: number;
        Message: string;
    };
    TargetData: {
        TargetID: UUID;
    }[];

    getSize(): number
    {
        return (this.Info['Message'].length + 1) + ((16) * this.TargetData.length) + 34;
    }

}
