// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {Vector3} from '../Vector3';
import {Quaternion} from '../Quaternion';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class TelehubInfoPacket implements Packet
{
    name = 'TelehubInfo';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = 4294901770;

    TelehubBlock: {
        ObjectID: UUID;
        ObjectName: string;
        TelehubPos: Vector3;
        TelehubRot: Quaternion;
    };
    SpawnPointBlock: {
        SpawnPointPos: Vector3;
    }[];

    getSize(): number
    {
        return (this.TelehubBlock['ObjectName'].length + 1) + ((12) * this.SpawnPointBlock.length) + 41;
    }

}
