// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class TransferInfoPacket implements Packet
{
    name = 'TransferInfo';
    flags = MessageFlags.Zerocoded | MessageFlags.FrequencyLow;
    id = 4294901914;

    TransferInfo: {
        TransferID: UUID;
        ChannelType: number;
        TargetType: number;
        Status: number;
        Size: number;
        Params: string;
    };

    getSize(): number
    {
        return (this.TransferInfo['Params'].length + 2) + 32;
    }

}
