// This file has been automatically generated by writePacketClasses.js

import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class UnsubscribeLoadPacket implements Packet
{
    name = 'UnsubscribeLoad';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = 4294901768;


    getSize(): number
    {
        return 0;
    }

     writeToBuffer(buf: Buffer, pos: number): number
     {
         return 0;
     }

     readFromBuffer(buf: Buffer, pos: number): number
     {
         return 0;
     }
}

