// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class UpdateSimulatorPacket implements Packet
{
    name = 'UpdateSimulator';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = 4294901777;

    SimulatorInfo: {
        RegionID: UUID;
        SimName: string;
        EstateID: number;
        SimAccess: number;
    };

    getSize(): number
    {
        return (this.SimulatorInfo['SimName'].length + 1) + 21;
    }

}
