// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {Vector3} from '../Vector3';
import Long = require('long');
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class UpdateParcelPacket implements Packet
{
    name = 'UpdateParcel';
    flags = MessageFlags.Trusted | MessageFlags.Zerocoded | MessageFlags.FrequencyLow;
    id = 4294901981;

    ParcelData: {
        ParcelID: UUID;
        RegionHandle: Long;
        OwnerID: UUID;
        GroupOwned: boolean;
        Status: number;
        Name: string;
        Description: string;
        MusicURL: string;
        RegionX: number;
        RegionY: number;
        ActualArea: number;
        BillableArea: number;
        ShowDir: boolean;
        IsForSale: boolean;
        Category: number;
        SnapshotID: UUID;
        UserLocation: Vector3;
        SalePrice: number;
        AuthorizedBuyerID: UUID;
        AllowPublish: boolean;
        MaturePublish: boolean;
    };

    getSize(): number
    {
        return (this.ParcelData['Name'].length + 1 + this.ParcelData['Description'].length + 1 + this.ParcelData['MusicURL'].length + 1) + 111;
    }

}
