// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class VelocityInterpolateOnPacket implements Packet
{
    name = 'VelocityInterpolateOn';
    flags = MessageFlags.FrequencyLow;
    id = 4294901885;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };

    getSize(): number
    {
        return 32;
    }

}
