// This file has been automatically generated by writePacketClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class ViewerEffectPacket implements Packet
{
    name = 'ViewerEffect';
    flags = MessageFlags.Zerocoded | MessageFlags.FrequencyMedium;
    id = 65297;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    Effect: {
        ID: UUID;
        AgentID: UUID;
        Type: number;
        Duration: number;
        Color: Buffer;
        TypeData: string;
    }[];

    getSize(): number
    {
        return ((this.calculateVarVarSize(this.Effect, 'TypeData', 1) + 41) * this.Effect.length) + 33;
    }

    calculateVarVarSize(block: object[], paramName: string, extraPerVar: number): number
    {
        let size = 0;
        block.forEach((bl: any) =>
        {
            size += bl[paramName].length + extraPerVar;
        });
        return size;
    }

}
