// This file has been automatically generated by writePacketClasses.js

import {MessageFlags} from '../../enums/MessageFlags';
import {Packet} from '../Packet';

export class ViewerFrozenMessagePacket implements Packet
{
    name = 'ViewerFrozenMessage';
    flags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = 4294901897;

    FrozenData: {
        Data: boolean;
    };

    getSize(): number
    {
        return 1;
    }

     writeToBuffer(buf: Buffer, pos: number): number
     {
         const startPos = pos;
         buf.writeUInt8((this.FrozenData['Data']) ? 1 : 0, pos++);
         return pos - startPos;
     }

     readFromBuffer(buf: Buffer, pos: number): number
     {
         const startPos = pos;
         const newObjFrozenData: {
             Data: boolean
         } = {
             Data: false
         };
         newObjFrozenData['Data'] = (buf.readUInt8(pos++) === 1);
         this.FrozenData = newObjFrozenData;
         return pos - startPos;
     }
}

