export enum AssetType
{
    Unknown = -1,
    Texture = 0,
    Sound = 1,
    CallingCard = 2,
    Landmark = 3,
    Script = 4,
    Clothing = 5,
    Object = 6,
    Notecard = 7,
    Folder = 8,
    Category = 8,
    LSLText = 10,
    LSLBytecode = 11,
    TextureTGA = 12,
    Bodypart = 13,

    SoundWAV = 17,
    ImageTGA = 18,
    ImageJPEG = 19,
    Animation = 20,
    Gesture = 21,
    Simstate = 22,
    Link = 24,
    LinkFolder = 25,
    MarketplaceFolder = 26,
    Widget = 40,
    Person = 46,
    Mesh = 49,
    Settings = 56,
    Material = 57
}
