export enum AssetTypeLL
{
    texture = 0,
    sound = 1,
    callcard = 2,
    landmark = 3,
    script = 4,
    clothing = 5,
    object = 6,
    notecard = 7,
    category = 8,
    lsltext = 10,
    lslbyte = 11,
    txtr_tga = 12,
    bodypart = 13,
    snd_wav = 17,
    img_tga = 18,
    jpeg = 19,
    animatn = 20,
    gesture = 21,
    simstate = 22,
    link = 24,
    link_f = 25,
    mesh = 49
}