export enum InventoryType
{
    Unknown = -1,
    Texture = 0,
    Sound = 1,
    CallingCard = 2,
    Landmark = 3,
    Script = 4,
    Clothing = 5,
    Object = 6,
    Notecard = 7,
    Category = 8,
    Folder = 8,
    RootCategory = 9,
    LSL = 10,
    Bodypart = 13,
    Snapshot = 15,
    Attachment = 17,
    Wearable = 18,
    Animation = 19,
    Gesture = 20,
    Mesh = 22,
    Widget = 23,
    Person = 24,
    Settings = 25,
    Material = 26,
}
