export enum ParcelFlags
{
    None = 0,
    AllowFly = 1 << 0,
    AllowOtherScripts = 1 << 1,
    ForSale = 1 << 2,
    AllowLandmark = 1 << 3,
    AllowTerraform = 1 << 4,
    AllowDamage = 1 << 5,
    CreateObjects = 1 << 6,
    ForSaleObjects = 1 << 7,
    UseAccessGroup = 1 << 8,
    UseAccessList = 1 << 9,
    UseBanList = 1 << 10,
    UsePassList = 1 << 11,
    ShowDirectory = 1 << 12,
    AllowDeedToGroup = 1 << 13,
    ContributeWithDeed = 1 << 14,
    SoundLocal = 1 << 15,
    SellParcelObjects = 1 << 16,
    AllowPublish = 1 << 17,
    MaturePublish = 1 << 18,
    UrlWebPage = 1 << 19,
    UrlRawHtml = 1 << 20,
    RestrictPushObject = 1 << 21,
    DenyAnonymous = 1 << 22,
    LindenHome = 1 << 23,
    DenyTransacted = 1 << 24,
    AllowGroupScripts = 1 << 25,
    CreateGroupObjects = 1 << 26,
    AllowAPrimitiveEntry = 1 << 27,
    AllowGroupObjectEntry = 1 << 28,
    AllowVoiceChat = 1 << 29,
    UseEstateVoiceChan = 1 << 30,
    DenyAgeUnverified = 1 << 31
}