// This file has been automatically generated by writeMessageClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {MessageBase} from '../MessageBase';
import {Message} from '../../enums/Message';

export class AgentAlertMessageMessage implements MessageBase
{
    name = 'AgentAlertMessage';
    messageFlags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = Message.AgentAlertMessage;

    AgentData: {
        AgentID: UUID;
    };
    AlertData: {
        Modal: boolean;
        Message: Buffer;
    };

    getSize(): number
    {
        return (this.AlertData['Message'].length + 1) + 17;
    }

    writeToBuffer(buf: Buffer, pos: number): number
    {
        const startPos = pos;
        this.AgentData['AgentID'].writeToBuffer(buf, pos);
        pos += 16;
        buf.writeUInt8((this.AlertData['Modal']) ? 1 : 0, pos++);
        buf.writeUInt8(this.AlertData['Message'].length, pos++);
        this.AlertData['Message'].copy(buf, pos);
        pos += this.AlertData['Message'].length;
        return pos - startPos;
    }

    readFromBuffer(buf: Buffer, pos: number): number
    {
        const startPos = pos;
        let varLength = 0;
        const newObjAgentData: {
            AgentID: UUID
        } = {
            AgentID: UUID.zero()
        };
        newObjAgentData['AgentID'] = new UUID(buf, pos);
        pos += 16;
        this.AgentData = newObjAgentData;
        const newObjAlertData: {
            Modal: boolean,
            Message: Buffer
        } = {
            Modal: false,
            Message: Buffer.allocUnsafe(0)
        };
        newObjAlertData['Modal'] = (buf.readUInt8(pos++) === 1);
        varLength = buf.readUInt8(pos++);
        newObjAlertData['Message'] = buf.slice(pos, pos + varLength);
        pos += varLength;
        this.AlertData = newObjAlertData;
        return pos - startPos;
    }
}

