// This file has been automatically generated by writeMessageClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {MessageBase} from '../MessageBase';
import {Message} from '../../enums/Message';

export class GetScriptRunningMessage implements MessageBase
{
    name = 'GetScriptRunning';
    messageFlags = MessageFlags.FrequencyLow;
    id = Message.GetScriptRunning;

    Script: {
        ObjectID: UUID;
        ItemID: UUID;
    };

    getSize(): number
    {
        return 32;
    }

    writeToBuffer(buf: Buffer, pos: number): number
    {
        const startPos = pos;
        this.Script['ObjectID'].writeToBuffer(buf, pos);
        pos += 16;
        this.Script['ItemID'].writeToBuffer(buf, pos);
        pos += 16;
        return pos - startPos;
    }

    readFromBuffer(buf: Buffer, pos: number): number
    {
        const startPos = pos;
        let varLength = 0;
        const newObjScript: {
            ObjectID: UUID,
            ItemID: UUID
        } = {
            ObjectID: UUID.zero(),
            ItemID: UUID.zero()
        };
        newObjScript['ObjectID'] = new UUID(buf, pos);
        pos += 16;
        newObjScript['ItemID'] = new UUID(buf, pos);
        pos += 16;
        this.Script = newObjScript;
        return pos - startPos;
    }
}

