// This file has been automatically generated by writeMessageClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {MessageBase} from '../MessageBase';
import {Message} from '../../enums/Message';

export class GrantGodlikePowersMessage implements MessageBase
{
    name = 'GrantGodlikePowers';
    messageFlags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = Message.GrantGodlikePowers;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    GrantData: {
        GodLevel: number;
        Token: UUID;
    };

    getSize(): number
    {
        return 49;
    }

    writeToBuffer(buf: Buffer, pos: number): number
    {
        const startPos = pos;
        this.AgentData['AgentID'].writeToBuffer(buf, pos);
        pos += 16;
        this.AgentData['SessionID'].writeToBuffer(buf, pos);
        pos += 16;
        buf.writeUInt8(this.GrantData['GodLevel'], pos++);
        this.GrantData['Token'].writeToBuffer(buf, pos);
        pos += 16;
        return pos - startPos;
    }

    readFromBuffer(buf: Buffer, pos: number): number
    {
        const startPos = pos;
        let varLength = 0;
        const newObjAgentData: {
            AgentID: UUID,
            SessionID: UUID
        } = {
            AgentID: UUID.zero(),
            SessionID: UUID.zero()
        };
        newObjAgentData['AgentID'] = new UUID(buf, pos);
        pos += 16;
        newObjAgentData['SessionID'] = new UUID(buf, pos);
        pos += 16;
        this.AgentData = newObjAgentData;
        const newObjGrantData: {
            GodLevel: number,
            Token: UUID
        } = {
            GodLevel: 0,
            Token: UUID.zero()
        };
        newObjGrantData['GodLevel'] = buf.readUInt8(pos++);
        newObjGrantData['Token'] = new UUID(buf, pos);
        pos += 16;
        this.GrantData = newObjGrantData;
        return pos - startPos;
    }
}

