// This file has been automatically generated by writeMessageClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {MessageBase} from '../MessageBase';
import {Message} from '../../enums/Message';

export class GroupProposalBallotMessage implements MessageBase
{
    name = 'GroupProposalBallot';
    messageFlags = MessageFlags.Deprecated | MessageFlags.FrequencyLow;
    id = Message.GroupProposalBallot;

    AgentData: {
        AgentID: UUID;
        SessionID: UUID;
    };
    ProposalData: {
        ProposalID: UUID;
        GroupID: UUID;
        VoteCast: string;
    };

    getSize(): number
    {
        return (this.ProposalData['VoteCast'].length + 1) + 64;
    }

    writeToBuffer(buf: Buffer, pos: number): number
    {
        const startPos = pos;
        this.AgentData['AgentID'].writeToBuffer(buf, pos);
        pos += 16;
        this.AgentData['SessionID'].writeToBuffer(buf, pos);
        pos += 16;
        this.ProposalData['ProposalID'].writeToBuffer(buf, pos);
        pos += 16;
        this.ProposalData['GroupID'].writeToBuffer(buf, pos);
        pos += 16;
        buf.writeUInt8(this.ProposalData['VoteCast'].length, pos++);
        buf.write(this.ProposalData['VoteCast'], pos);
        pos += this.ProposalData['VoteCast'].length;
        return pos - startPos;
    }

    readFromBuffer(buf: Buffer, pos: number): number
    {
        const startPos = pos;
        let varLength = 0;
        const newObjAgentData: {
            AgentID: UUID,
            SessionID: UUID
        } = {
            AgentID: UUID.zero(),
            SessionID: UUID.zero()
        };
        newObjAgentData['AgentID'] = new UUID(buf, pos);
        pos += 16;
        newObjAgentData['SessionID'] = new UUID(buf, pos);
        pos += 16;
        this.AgentData = newObjAgentData;
        const newObjProposalData: {
            ProposalID: UUID,
            GroupID: UUID,
            VoteCast: string
        } = {
            ProposalID: UUID.zero(),
            GroupID: UUID.zero(),
            VoteCast: ''
        };
        newObjProposalData['ProposalID'] = new UUID(buf, pos);
        pos += 16;
        newObjProposalData['GroupID'] = new UUID(buf, pos);
        pos += 16;
        varLength = buf.readUInt8(pos++);
        newObjProposalData['VoteCast'] = buf.toString('utf8', pos, pos + (varLength - 1));
        pos += varLength;
        this.ProposalData = newObjProposalData;
        return pos - startPos;
    }
}

