// This file has been automatically generated by writeMessageClasses.js

import Long = require('long');
import {MessageFlags} from '../../enums/MessageFlags';
import {MessageBase} from '../MessageBase';
import {Message} from '../../enums/Message';

export class NearestLandingRegionRequestMessage implements MessageBase
{
    name = 'NearestLandingRegionRequest';
    messageFlags = MessageFlags.Trusted | MessageFlags.FrequencyLow;
    id = Message.NearestLandingRegionRequest;

    RequestingRegionData: {
        RegionHandle: Long;
    };

    getSize(): number
    {
        return 8;
    }

    writeToBuffer(buf: Buffer, pos: number): number
    {
        const startPos = pos;
        buf.writeInt32LE(this.RequestingRegionData['RegionHandle'].low, pos);
        pos += 4;
        buf.writeInt32LE(this.RequestingRegionData['RegionHandle'].high, pos);
        pos += 4;
        return pos - startPos;
    }

    readFromBuffer(buf: Buffer, pos: number): number
    {
        const startPos = pos;
        let varLength = 0;
        const newObjRequestingRegionData: {
            RegionHandle: Long
        } = {
            RegionHandle: Long.ZERO
        };
        newObjRequestingRegionData['RegionHandle'] = new Long(buf.readInt32LE(pos), buf.readInt32LE(pos+4));
        pos += 8;
        this.RequestingRegionData = newObjRequestingRegionData;
        return pos - startPos;
    }
}

