// This file has been automatically generated by writeMessageClasses.js

import {UUID} from '../UUID';
import {MessageFlags} from '../../enums/MessageFlags';
import {MessageBase} from '../MessageBase';
import {Message} from '../../enums/Message';

export class RegionHandleRequestMessage implements MessageBase
{
    name = 'RegionHandleRequest';
    messageFlags = MessageFlags.FrequencyLow;
    id = Message.RegionHandleRequest;

    RequestBlock: {
        RegionID: UUID;
    };

    getSize(): number
    {
        return 16;
    }

    writeToBuffer(buf: Buffer, pos: number): number
    {
        const startPos = pos;
        this.RequestBlock['RegionID'].writeToBuffer(buf, pos);
        pos += 16;
        return pos - startPos;
    }

    readFromBuffer(buf: Buffer, pos: number): number
    {
        const startPos = pos;
        let varLength = 0;
        const newObjRequestBlock: {
            RegionID: UUID
        } = {
            RegionID: UUID.zero()
        };
        newObjRequestBlock['RegionID'] = new UUID(buf, pos);
        pos += 16;
        this.RequestBlock = newObjRequestBlock;
        return pos - startPos;
    }
}

