import type { PCode } from '../../enums/PCode';
import type { SoundFlags } from '../../enums/SoundFlags';
import type { GameObject } from '../public/GameObject';
import type { UUID } from '../UUID';
import type { Vector3 } from '../Vector3';
import type { Color4 } from '../Color4';
import type { Quaternion } from '../Quaternion';
import type { Vector4 } from '../Vector4';
import type { Tree } from '../../enums/Tree';
import type { ParticleSystem } from '../ParticleSystem';
import type { NameValue } from '../NameValue';
import type { TextureEntry } from '../TextureEntry';
import type { FlexibleData } from '../public/FlexibleData';
import type { LightData } from '../public/LightData';
import type { LightImageData } from '../public/LightImageData';
import type { SculptData } from '../public/SculptData';
import type { MeshData } from '../public/MeshData';

export interface IGameObjectData
{
    deleted: boolean;
    creatorID?: UUID;
    creationDate?: Long;
    baseMask?: number;
    ownerMask?: number;
    groupMask?: number;
    everyoneMask?: number;
    nextOwnerMask?: number;
    ownershipCost?: number;
    saleType?: number;
    salePrice?: number;
    aggregatePerms?: number;
    aggregatePermTextures?: number;
    aggregatePermTexturesOwner?: number;
    category: number;
    inventorySerial: number;
    itemID: UUID;
    folderID: UUID;
    fromTaskID: UUID;
    lastOwnerID: UUID;
    name?: string;
    description?: string;
    touchName?: string;
    sitName?: string;
    textureID?: string;
    resolvedAt?: number;
    resolvedInventory: boolean;
    totalChildren?: number;

    landImpact?: number;
    calculatedLandImpact?: number;
    physicaImpact?: number;
    resourceImpact?: number;
    linkResourceImpact?: number;
    linkPhysicsImpact?: number;
    limitingType?: string;

    children?: GameObject[];
    ID: number;
    FullID: UUID;
    ParentID?: number;
    OwnerID: UUID;
    IsAttachment: boolean;
    NameValue: Map<string, NameValue>;
    PCode: PCode;
    State?: number;
    CRC?: number;
    Material?: number;
    ClickAction?: number;
    Scale?: Vector3;
    Flags?: number;
    PathCurve?: number;
    ProfileCurve?: number;
    PathBegin?: number;
    PathEnd?: number;
    PathScaleX?: number;
    PathScaleY?: number;
    PathShearX?: number;
    PathShearY?: number;
    PathTwist?: number;
    PathTwistBegin?: number;
    PathRadiusOffset?: number;
    PathTaperX?: number;
    PathTaperY?: number;
    PathRevolutions?: number;
    PathSkew?: number;
    ProfileBegin?: number;
    ProfileEnd?: number;
    ProfileHollow?: number;
    TextureEntry?: TextureEntry;
    Text?: string;
    TextColor?: Color4;
    MediaURL?: string;
    JointType?: number;
    JointPivot?: Vector3;
    JointAxisOrAnchor?: Vector3;
    Position?: Vector3;
    Rotation?: Quaternion;
    CollisionPlane?: Vector4;
    Velocity?: Vector3;
    Acceleration?: Vector3;
    AngularVelocity?: Vector3;
    TreeSpecies?: Tree;
    Sound?: UUID;
    SoundGain?: number;
    SoundFlags?: SoundFlags;
    SoundRadius?: number;
    Particles?: ParticleSystem;
    FlexibleData?: FlexibleData;
    LightData?: LightData;
    LightImageData?: LightImageData;
    SculptData?: SculptData;
    MeshData?: MeshData;
    density?: number;
    friction?: number;
    gravityMultiplier?: number;
    physicsShapeType?: number;
    restitution?: number;
}
