import {UUID} from '../UUID';
import * as Long from 'long';
import {NameValue} from '../NameValue';
import {Vector3} from '../Vector3';
import {TextureEntry} from '../TextureEntry';
import {Color4} from '../Color4';
import {Quaternion} from '../Quaternion';
import {Vector4} from '../Vector4';
import {Tree} from '../../enums/Tree';
import {PCode, SoundFlags} from '../..';
import {ParticleSystem} from '../ParticleSystem';
import {GameObject} from '../public/GameObject';
import {FlexibleData} from '../public/FlexibleData';
import {LightData} from '../public/LightData';
import {LightImageData} from '../public/LightImageData';
import {SculptData} from '../public/SculptData';
import {MeshData} from '../public/MeshData';

export interface IGameObjectData
{
    deleted: boolean;
    creatorID?: UUID;
    creationDate?: Long;
    baseMask?: number;
    ownerMask?: number;
    groupMask?: number;
    everyoneMask?: number;
    nextOwnerMask?: number;
    ownershipCost?: number;
    saleType?: number;
    salePrice?: number;
    aggregatePerms?: number;
    aggregatePermTextures?: number;
    aggregatePermTexturesOwner?: number;
    category: number;
    inventorySerial: number;
    itemID: UUID;
    folderID: UUID;
    fromTaskID: UUID;
    lastOwnerID: UUID;
    name?: string;
    description?: string;
    touchName?: string;
    sitName?: string;
    textureID?: string;
    resolvedAt?: number;
    totalChildren?: number;

    landImpact?: number;
    calculatedLandImpact?: number;
    physicaImpact?: number;
    resourceImpact?: number;
    linkResourceImpact?: number;
    linkPhysicsImpact?: number;
    limitingType?: string;

    children?: GameObject[];
    ID: number;
    FullID: UUID;
    ParentID?: number;
    OwnerID: UUID;
    IsAttachment: boolean;
    NameValue: {[key: string]: NameValue};
    PCode: PCode;
    State?: number;
    CRC?: number;
    Material?: number;
    ClickAction?: number;
    Scale?: Vector3;
    Flags?: number;
    PathCurve?: number;
    ProfileCurve?: number;
    PathBegin?: number;
    PathEnd?: number;
    PathScaleX?: number;
    PathScaleY?: number;
    PathShearX?: number;
    PathShearY?: number;
    PathTwist?: number;
    PathTwistBegin?: number;
    PathRadiusOffset?: number;
    PathTaperX?: number;
    PathTaperY?: number;
    PathRevolutions?: number;
    PathSkew?: number;
    ProfileBegin?: number;
    ProfileEnd?: number;
    ProfileHollow?: number;
    TextureEntry?: TextureEntry;
    Text?: string;
    TextColor?: Color4;
    MediaURL?: string;
    JointType?: number;
    JointPivot?: Vector3;
    JointAxisOrAnchor?: Vector3;
    Position?: Vector3;
    Rotation?: Quaternion;
    CollisionPlane?: Vector4;
    Velocity?: Vector3;
    Acceleration?: Vector3;
    AngularVelocity?: Vector3;
    TreeSpecies?: Tree;
    Sound?: UUID;
    SoundGain?: number;
    SoundFlags?: SoundFlags;
    SoundRadius?: number;
    Particles?: ParticleSystem;
    FlexibleData?: FlexibleData;
    LightData?: LightData;
    LightImageData?: LightImageData;
    SculptData?: SculptData;
    MeshData?: MeshData;
    density?: number;
    friction?: number;
    gravityMultiplier?: number;
    physicsShapeType?: number;
    restitution?: number;
}